# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f36cf3884e84b62a5cffa94bc01952d3"
name = "project-dev-shopify"
handle = "project-dev-shopify"
application_url = "https://app-shopify.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "novaon.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://app-shopify.onrender.com/auth/callback",
  "https://app-shopify.onrender.com/auth/shopify/callback",
  "https://app-shopify.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
