# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dfaca6f08fe297de967b16935ad94860"
name = "project-dev-fonend"
handle = "project-dev-fonend"
application_url = "https://handbags-blades-belize-girls.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "minhvv.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://handbags-blades-belize-girls.trycloudflare.com/auth/callback",
  "https://handbags-blades-belize-girls.trycloudflare.com/auth/shopify/callback",
  "https://handbags-blades-belize-girls.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
